## <u> RL Lab Assignment - 3 ( Value Iteration and Policy Iteration) </u>

### Name : Arvind Pandit
### Roll No. : 211022001

### <u> Value Iteration Algorithm </u>

![picture](https://drive.google.com/uc?export=view&id=1dbKugsiHLb_UuaxqikpkAcunyiWy5Qxd)

### <u> Policy Iteration Algorithm </u>

![picture](https://drive.google.com/uc?export=view&id=1LqsCcUE8KUjCWlIqu1q2FPwk1MtqpKiL)


Reference: [Value iteration](http://incompleteideas.net/book/ebook/node44.html) [Policy Iteration](http://incompleteideas.net/book/ebook/node43.html)


# Problem 1.

Here we have taken a very simple problem of Markov Decision Process.

![picture](https://drive.google.com/uc?export=view&id=1H-JZZ_DjtxIfZres9OOu8SasgC8SYkTC)


There are five 2D tiles which represent the state of MDP.

State = {0,1,2,3,4,5}

The reward of each state is given by [-1, -1, 10, -1, -1] and the goal is to reach terminal state 3rd which have reward of 10.

Reward = {-1, -1, 10, -1, -1}

The allowed action are left and right

Action = {0,1} where 0=left and 1=right

Here the agent have to collect the maximum reward and reach to the terminal state 3rd.

In [ ]:
import numpy as np

## Problem definations ###

n=5 # no. of states {0-...-4}
m=2 # no. of actions 0-left 1-right
rewards = np.array([-1, -1, 10, -1, -1]) # Reward in each state

# MDP settings

epsilon = 0.004 # small value 
policy_iter=10000
value_iter=10000
r=0.9 # discount factor gamma

In [ ]:
#Transition Probability Matrix

Prob_a1 = np.matrix([[0.9, 0.1, 0, 0, 0], 
                     [0.9, 0, 0.1, 0, 0],
                     [0, 0, 0, 0, 0],
                     [0, 0, 0.9, 0, 0.1],
                     [0, 0, 0, 0.9, 0.1]])

Prob_a2 = np.matrix([[0.1, 0.9, 0, 0, 0], 
                     [0.1, 0, 0.9, 0, 0],
                     [0, 0, 0, 0, 0],
                     [0, 0, 0.1, 0, 0.9],
                     [0, 0, 0, 0.1, 0.9]])

print("Probability Transition matrix for action a1-left\n")
print(Prob_a1)
print("\n")
print("Probability Transition matrix for action a2-right\n")
print(Prob_a2)

Probability Transition matrix for action a1-left

[[0.9 0.1 0.  0.  0. ]
 [0.9 0.  0.1 0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.9 0.  0.1]
 [0.  0.  0.  0.9 0.1]]


Probability Transition matrix for action a2-right

[[0.1 0.9 0.  0.  0. ]
 [0.1 0.  0.9 0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.1 0.  0.9]
 [0.  0.  0.  0.1 0.9]]


### 1. Value Iteration

In [ ]:
states = np.arange(n)
action = np.arange(m) 
P = np.array([Prob_a1, Prob_a2]) # to access Prob[action][intial][next]
V_prev=np.zeros(n) # Initialize value fucntion as 0
mu = [None, None, None, None, None] # Initialize policy
for i in range(value_iter):
  max_diff=0 # Initialize max_diff
  diff_of_value_function=np.zeros(n) # difference between current value function and previous value fucntion
  V_curr = np.zeros(n) # intialize current value fucntion as zero

  for s in states:
    total_exp_reward = np.zeros(m) # intilize reward as zero

    for a in action: 
      total_exp_reward[a] = rewards[s] + r*np.sum([P[a][s][next_state]*V_prev[next_state] for next_state in states]) # Total expected reward collected by taking action a in state s
      
    V_curr[s]= np.max(total_exp_reward) # according to the bellman equation
    mu[s]= np.argmax(total_exp_reward) # get the action which have given max reward
    diff_of_value_function[s]=np.abs(V_prev[s]-V_curr[s]) # diff between each element of V

  V_prev=V_curr
  max_diff = np.max(diff_of_value_function) # bcoz of l-infinity norm

  if max_diff < epsilon: # Stop if diff is less than epsilon
    print("No. of iterations in Value Iterions = "+str(i + 1))
    break

print("For Value iteration")
print("Optimal Value function V* = "+str(V_curr))
print("Optimal policy mu* = "+ str(mu))




No. of iterations in Value Iterions = 10
For Value iteration
Optimal Value function V* = [ 5.67496513  7.61064654 10.          7.61064654  5.67496513]
Optimal policy mu* = [1, 1, 0, 0, 0]


### 2. Policy Iterations

In [ ]:
V_prev=np.zeros(n) # Initialize arbitary value fucntion as [0 0 0 0 0]
mu=np.zeros(n) # Intilize an arbitatry policy [0 0 0 0 0]

for i in range(policy_iter):
  optimal_policy = True

  # Policy Evaluation
  
  for j in range(value_iter):
    max_diff=0 # Initialize max_diff
    diff_of_value_function=np.zeros(n) # difference between current value function and previous value fucntion    
    V_curr = np.zeros(n) # intialize current value fucntion as zero

    for s in states:
      V_curr[s]  = rewards[s] + r*np.sum([P[int(mu[s])][s][next_state]*V_prev[next_state] for next_state in states]) # Total expected reward collected by taking action a in state s according to policy mu
      diff_of_value_function[s]=np.abs(V_prev[s]-V_curr[s]) # diff between each element of V

    V_prev=V_curr
    max_diff = np.max(diff_of_value_function) # bcoz of l-infinity norm

    if max_diff < epsilon:
      print("No. of iterations for Vmu"+str(i)+" = "+str(j + 1))
      break

  # Policy Improvement

  for s in states:
    maximum_value = V_prev[s]
    for a in action:
      value  = rewards[s] + r*np.sum([P[a][s][next_state]*V_prev[next_state] for next_state in states]) # Q(u,a) Total expected reward collected by taking action a in state s and then according to policy mu
      if value > maximum_value and mu[s] != a and s!=3 :
        mu[s]=a
        maximum_value = value
        optimal_policy = False
  
  if optimal_policy :
    print("No. of iterations in Policy Iterions = "+str(i + 1))
    break

print("For Policy iteration")
print("Optimal Value function V* = "+str(V_curr))
print("Optimal policy mu* = "+ str(mu))

No. of iterations for Vmu0 = 49
No. of iterations for Vmu1 = 9
No. of iterations in Policy Iterions = 2
For Policy iteration
Optimal Value function V* = [ 5.67450141  7.61052229 10.          7.61079919  5.67554653]
Optimal policy mu* = [1. 1. 0. 0. 0.]


The Optimal Policy is mu=[1 1 0 0 0]  s.t  [right right left left left]

![picture](https://drive.google.com/uc?export=view&id=1k89bXK2ptG4Gd5FRXLq4LxIsJ4xSuqtx)

### 3. Verification by choosing Random Policy

In [ ]:

############################### Verification by choosing Random Policy ###############################################
print("Average collected reward with optimal policy mu "+ str(mu) + " is " + str(np.average(V_curr)))
for k in range(3):
  print("\n")
  rand_mu = np.random.choice(m, n)
  for j in range(value_iter):
      max_diff=0 # Initialize max_diff
      diff_of_value_function=np.zeros(n) # difference between current value function and previous value fucntion    
      V_curr = np.zeros(n) # intialize current value fucntion as zero

      for s in states:
        V_curr[s]  = rewards[s] + r*np.sum([P[int(rand_mu[s])][s][next_state]*V_prev[next_state] for next_state in states]) # Total expected reward collected by taking action a in state s according to policy mu
        diff_of_value_function[s]=np.abs(V_prev[s]-V_curr[s]) # diff between each element of V

      V_prev=V_curr
      max_diff = np.max(diff_of_value_function) # bcoz of l-infinity norm

      if max_diff < epsilon:
        break
  print("Average collected reward with random policy mu_" + str(k) + " "+ str(rand_mu) + " is " + str(np.average(V_curr)))

#################################### End ###################################################################################

Average collected reward with optimal policy mu [1. 1. 0. 0. 0.] is 7.314273885011818


Average collected reward with random policy mu_0 [1 1 1 1 0] is 3.104499557903851


Average collected reward with random policy mu_1 [0 1 0 1 1] is -0.13949453794473196


Average collected reward with random policy mu_2 [1 0 0 0 1] is 1.432984378709557


# Problem 2.
We have taken a grid problem of Markov Decision Process.

Here the robot starts from the state 0 and there are walls in state (2,3,8,9) and the final destination of the robot is state 12.

The movement of the robot have the randomness such that it will go to the commanded direction with probability 0.7 and other 3 direction with each having probability 0.1.

![picture](https://drive.google.com/uc?export=view&id=1bIpVHiiPsghTGeZ4f_EGd1CLux6HUlIv)

There are 16 grids which represent the state of MDP.

State = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15}

The reward of each state is given by {-1,-1,0,0,-1,-1,-1,-1,0,0,-1,-1,10,-1,-1,-1} and the goal is to reach terminal state 12th which have reward of 10.

Each step will cost 1.

Reward = {-1,-1,0,0,-1,-1,-1,-1,0,0,-1,-1,10,-1,-1,-1}

The allowed action are up,down,left and right

Action = {0,1,2,3} where 0=up,1=down,2=left,3=right

Here the agent have to collect the maximum reward and reach to the terminal state 12 avoiding the collision with walls.


In [ ]:
import numpy as np

## Problem definations ###

n=16 # no. of states {0-...-15}
m=4 # no. of actions 0-up,1-down,2-left,3-right
rewards = np.array([-1,-1,0,0,-1,-1,-1,-1,0,0,-1,-1,10,-1,-1,-1])

## Define wall_states and terminals state

wall = np.array([2,3,8,9])
terminal=12

# MDP settings

epsilon = 0.004 # small value 
policy_iter=10000
value_iter=10000
r=0.9 # discount factor gamma

In [ ]:
def PowerOfTwo(n):
    if (n == 0):
        return False,0
    counter=0
    while (n != 1):
      if (n % 2 != 0):
        return False,0
      n = n // 2
      counter+=1       
    return True,counter

In [ ]:
states = np.arange(n)
action = np.arange(m) 
P_u = np.zeros((n,n))
P_d = np.zeros((n,n))
P_l = np.zeros((n,n))
P_r = np.zeros((n,n))

c=0 # column variable
column = PowerOfTwo(n)
if(column[0]):
    c=column[1]
else:
    print('State is not a power of 2 please give a square grid problem')

P=np.array([P_u,P_d,P_l,P_r])

u_l = np.array([z*c+(c-1) for z in range(c)]) # [3,7,11,15]
d_l = np.array([z*c for z in range(c)]) #  [0,4,8,12]
l_l = np.array([z for z in range(c)]) # [0,1,2,3]
r_l = np.array([n-(1+z) for z in range(c)]) # [12,13,14,15]


a=0
## For action up a=0
for s in states:
  if s==terminal or s in wall :
    P[a][s][s]=1
    continue
  if s in u_l or s+1 in wall:
      P[a][s][s]+=0.7
  else:
      P[a][s][s+1]=0.7
  
  if s in d_l:
      P[a][s][s]+=0.1
  else:
      P[a][s][s-1]=0.1
  
  if s in l_l:
      P[a][s][s]+=0.1
  else:
      P[a][s][s-c]=0.1
  
  if s in r_l:
      P[a][s][s]+=0.1
  else:
      P[a][s][s+c]=0.1
    
a=1
## For action down a=0
for s in states:
  if s==terminal:
    P[a][s][s]=1
    continue
  if s in u_l:
      P[a][s][s]+=0.1
  else:
      P[a][s][s+1]=0.1
  
  if s in d_l or s-1 in wall:
      P[a][s][s]+=0.7
  else:
      P[a][s][s-1]=0.7
  
  if s in l_l:
      P[a][s][s]+=0.1
  else:
      P[a][s][s-c]=0.1
  
  if s in r_l:
      P[a][s][s]+=0.1
  else:
      P[a][s][s+c]=0.1

a=2
## For action left a=0
for s in states:
  if s==terminal or s in wall :
    P[a][s][s]=1
    continue
  if s in u_l:
      P[a][s][s]+=0.1
  else:
      P[a][s][s+1]=0.1
  
  if s in d_l:
      P[a][s][s]+=0.1
  else:
      P[a][s][s-1]=0.1
  
  if s in l_l or s-c in wall:
      P[a][s][s]+=0.7
  else:
      P[a][s][s-c]=0.7
  
  if s in r_l:
      P[a][s][s]+=0.1
  else:
      P[a][s][s+c]=0.1

a=3
## For action right a=0
for s in states:
  if s==terminal or s in wall :
    P[a][s][s]=1
    continue
  if s in u_l:
      P[a][s][s]+=0.1
  else:
      P[a][s][s+1]=0.1
  
  if s in d_l:
      P[a][s][s]+=0.1
  else:
      P[a][s][s-1]=0.1
  
  if s in l_l:
      P[a][s][s]+=0.1
  else:
      P[a][s][s-c]=0.1
  
  if s in r_l or s+c in wall:
      P[a][s][s]+=0.7
  else:
      P[a][s][s+c]=0.7

print("Probability Transition matrix for action a1-up\n")
print(P[0])
print("\n")
print("Probability Transition matrix for action a2-down\n")
print(P[1])
print("\n")
print("Probability Transition matrix for action a3-left\n")
print(P[2])
print("\n")
print("Probability Transition matrix for action a4-right\n")
print(P[3])

Probability Transition matrix for action a1-up

[[0.2 0.7 0.  0.  0.1 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.1 0.8 0.  0.  0.  0.1 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.1 0.  0.  0.  0.1 0.7 0.  0.  0.1 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.1 0.  0.  0.1 0.  0.7 0.  0.  0.1 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.1 0.  0.  0.1 0.  0.7 0.  0.  0.1 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.1 0.  0.  0.1 0.7 0.  0.  0.  0.1 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.1 0.  0.  0.1 0.  0.7 0.  0.  0.1 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.1 0.  0.  0.1 0.7 0.  0.  0.  0.1]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.1 0.  0.  0.1 0.1 0.7 0. ]
 [0.  0.  0.  

### 1. Value Iteration

In [ ]:
V_prev=np.zeros(n) # Initialize value fucntion as 0
mu = [None for i in range(n)] # Initialize policy
for i in range(value_iter):
  max_diff=0 # Initialize max_diff
  diff_of_value_function=np.zeros(n) # difference between current value function and previous value fucntion
  V_curr = np.zeros(n) # intialize current value fucntion as zero

  for s in states:
    total_exp_reward = np.zeros(m) # intilize reward as zero

    for a in action: 
      total_exp_reward[a] = rewards[s] + r*np.sum([P[a][s][next_state]*V_prev[next_state] for next_state in states]) # Total expected reward collected by taking action a in state s
      
    V_curr[s]= np.max(total_exp_reward) # according to the bellman equation
    mu[s]= np.argmax(total_exp_reward) # get the action which have given max reward
    diff_of_value_function[s]=np.abs(V_prev[s]-V_curr[s]) # diff between each element of V

  V_prev=V_curr
  max_diff = np.max(diff_of_value_function) # bcoz of l-infinity norm

  if max_diff < epsilon: # Stop if diff is less than epsilon
    print("No. of iterations in Value Iterions = "+str(i + 1))
    break

# print(V_curr)
# print(mu)

policy = []
for p in mu:
  if p==0:
    policy.append("up")
  elif p==1:
    policy.append("down")
  elif p==2:
    policy.append("left")
  else:
    policy.append("right")

policy[terminal]="nan"
for w in wall:
  policy[int(w)]="nan"


print("For Value iteration")
print("Optimal Value function V* = "+str(V_curr))
print("Optimal policy mu* = "+ str(mu))
print("Optimal policy"+str(policy))



No. of iterations in Value Iterions = 76
For Value iteration
Optimal Value function V* = [21.89782805 24.80772769 22.53287879 16.14270632 26.55055866 31.07872535
 38.0726069  34.11590598 40.15483901 38.60073338 49.49279352 43.12606991
 99.96670104 78.15737539 63.03837479 51.94169849]
Optimal policy mu* = [3, 3, 1, 1, 0, 0, 3, 3, 1, 1, 3, 3, 0, 1, 1, 1]
Optimal policy['right', 'right', 'nan', 'nan', 'up', 'up', 'right', 'right', 'nan', 'nan', 'right', 'right', 'nan', 'down', 'down', 'down']


### 2. Policy Iteration

In [ ]:
mu=np.zeros(n) # Intilize an arbitatry policy

for i in range(policy_iter):
  optimal_policy = True

  # Policy Evaluation
  
  for j in range(value_iter):
    max_diff=0 # Initialize max_diff
    diff_of_value_function=np.zeros(n) # difference between current value function and previous value fucntion    
    V_curr = np.zeros(n) # intialize current value fucntion as zero

    for s in states:
      V_curr[s]  = rewards[s] + r*np.sum([P[int(mu[s])][s][next_state]*V_prev[next_state] for next_state in states]) # Total expected reward collected by taking action a in state s according to policy mu
      diff_of_value_function[s]=np.abs(V_prev[s]-V_curr[s]) # diff between each element of V

    V_prev=V_curr
    max_diff = np.max(diff_of_value_function) # bcoz of l-infinity norm

    if max_diff < epsilon:
      print("No. of iterations for Vmu"+str(i)+" = "+str(j + 1))
      break

  # Policy Improvement

  for s in states:
    maximum_value = V_prev[s]
    for a in action:
      value  = rewards[s] + r*np.sum([P[a][s][next_state]*V_prev[next_state] for next_state in states]) # Total expected reward collected by taking action a in state s according to policy mu
      if value > maximum_value and mu[s] != a and s!=terminal :
        mu[s]=a
        maximum_value = value
        optimal_policy = False
  # print(mu)
  if optimal_policy :
    print("No. of iterations in Policy Iterions = "+str(i + 1))
    break



# print(V_curr)
# print(mu)

policy = []
for p in mu:
  if p==0:
    policy.append("up")
  elif p==1:
    policy.append("down")
  elif p==2:
    policy.append("left")
  else:
    policy.append("right")

policy[terminal]="nan"
for w in wall:
  policy[int(w)]="nan"

print("For Value iteration")
print("Optimal Value function V* = "+str(V_curr))
print("Optimal policy mu* = "+ str(mu))
print("Optimal policy"+str(policy))


No. of iterations for Vmu0 = 67
No. of iterations for Vmu1 = 28
No. of iterations for Vmu2 = 45
No. of iterations for Vmu3 = 36
No. of iterations in Policy Iterions = 4
For Value iteration
Optimal Value function V* = [ 21.92829068  24.83823287  22.5612402   16.15729915  26.58141653
  31.10992607  38.10416901  34.14586757  40.18609368  38.63246463
  49.52532705  43.15841139 100.          78.19043061  63.07129906
  51.9744841 ]
Optimal policy mu* = [3. 3. 1. 1. 0. 0. 3. 3. 1. 1. 3. 3. 0. 1. 1. 1.]
Optimal policy['right', 'right', 'nan', 'nan', 'up', 'up', 'right', 'right', 'nan', 'nan', 'right', 'right', 'nan', 'down', 'down', 'down']


![picture](https://drive.google.com/uc?export=view&id=1OBD-npliwSZ1nswxDuBaUbMsFvqw58s2)


### 3. Verification by choosing Random Policy

In [ ]:
############################### Verification by choosing Random Policy ###############################################
print("Verification by choosing Random Policy")
print("Average collected reward with optimal policy mu "+ str(mu) + " is " + str(np.average(V_curr)))
for k in range(5):
  print("\n")
  rand_mu = np.random.choice(m,n)
  for j in range(value_iter):
      max_diff=0 # Initialize max_diff
      diff_of_value_function=np.zeros(n) # difference between current value function and previous value fucntion    
      V_curr = np.zeros(n) # intialize current value fucntion as zero

      for s in states:
        V_curr[s]  = rewards[s] + r*np.sum([P[int(rand_mu[s])][s][next_state]*V_prev[next_state] for next_state in states]) # Total expected reward collected by taking action a in state s according to policy mu
        diff_of_value_function[s]=np.abs(V_prev[s]-V_curr[s]) # diff between each element of V

      V_prev=V_curr
      max_diff = np.max(diff_of_value_function) # bcoz of l-infinity norm

      if max_diff < epsilon:
        break
  print("Average collected reward with random policy mu "+ str(rand_mu) + " is " + str(np.average(V_curr)))

Verification by choosing Random Policy
Average collected reward with optimal policy mu [3. 3. 1. 1. 0. 0. 3. 3. 1. 1. 3. 3. 0. 1. 1. 1.] is 42.51030953722727


Average collected reward with random policy mu [3 0 3 2 0 1 2 2 1 2 3 0 1 1 1 1] is 23.18138200974328


Average collected reward with random policy mu [1 3 3 0 0 1 3 1 2 2 0 2 2 1 0 2] is 7.472441067717258


Average collected reward with random policy mu [3 0 1 1 2 0 0 0 0 3 0 0 0 1 2 1] is 6.843661265486373


Average collected reward with random policy mu [1 2 2 1 3 3 0 2 3 0 3 3 0 2 3 3] is 4.833853267800601


Average collected reward with random policy mu [3 3 0 1 0 0 2 0 0 3 1 1 1 2 0 1] is 4.288022366768863
